Add seededRandom.js
CSE-210-Team-11/cse210-fa24-group-11 pull request #57
Opened 2024-11-27 20:20 UTC by Earth34r

2024-11-27 20:50 UTC, SirKanaad26 commented on src/utils/seededRandom.js
> +function MurmurHash3(string) {
The function is MurmurHash3,

2024-11-27 20:51 UTC, SirKanaad26 commented on src/utils/seededRandom.js
> +// Define the Murmur3Hash function
The name of the function is MurmurHash3, it's a non-cryptographic hash function - maybe rename the comment!

2024-11-27 20:59 UTC, SirKanaad26 commented on src/utils/seededRandom.js
> +	for (i, hash = 1779033703 ^ string.length; i < string.length; i++) {
The MurmurHash3 function that I know of, is a bit different from the one you have created - I am not sure as to what the return value of the hash function is? Is it a 32 bit hash? Because it looks like a 16 bit hash from the return value you have suggested. Maybe refer to [this](https://github.com/garycourt/murmurhash-js/blob/master/murmurhash3_gc.js) implementation that I found on Github, if not, here's a [Github Gist](https://gist.github.com/SirKanaad26/03183208d75082485ab478bdd27d3ad4) of Claude's take on MurmurHash3 that uses the original MurmurHash3 by Austin Appleby. Alternatively, we can rename the function to something else? Say BackStreetBoysHashMark1 😃?

2024-11-27 21:03 UTC, SirKanaad26 commented on src/utils/seededRandom.js
> +// Define the Mulberry32 function
Similarly, Mulberry32 takes a 32-bit integer as input, here's Claude's take in a [Github Gist](https://gist.github.com/SirKanaad26/4f108f3a4acee22771d7e0a926ad875d). Alternatively, rename this function!

2024-11-27 21:04 UTC, SirKanaad26 commented on src/utils/seededRandom.js
> +export function getSeededRandomInt(seed) {
Function looks good to me!

2024-11-27 21:04 UTC, SirKanaad26 commented on src/utils/seededRandom.js
> +export function getSeededRandomFloat(seed) {
Function looks good to me!

2024-11-27 21:06 UTC, SirKanaad26 requested changes
I was going through the library functions available and I found these:

- https://www.npmjs.com/package/random-seed
- https://www.npmjs.com/package/rand-seed
- https://www.npmjs.com/package/seedrandom

The last one's got the greatest number of weekly downloads. Do we need to write our own random number generator or can we use one of these dependencies. We need to research on this!

2024-11-27 21:39 UTC, Earth34r commented on src/utils/seededRandom.js
> +	for (i, hash = 1779033703 ^ string.length; i < string.length; i++) {
This version comes from this article: https://www.delftstack.com/howto/javascript/javascript-random-seed-to-generate-random/

It must be a simplified algorithm, all it is being used for is to generate a hash from a string to be used as a seed for Mulberry32.

2024-11-29 21:21 UTC, lezhangleonard requested changes
`src/__tests__/seededRandom.test.js` should be in `src/__tests__/utils/seededRandom.test.js`

2024-11-29 21:24 UTC, Earth34r commented on src/__tests__/seededRandom.test.js
Updated, please review

2024-11-29 21:26 UTC, lezhangleonard approved these changes
Looks good now

2024-11-29 22:11 UTC, SirKanaad26 approved these changes
The changes look better this time!

2024-11-29 23:08 UTC, jain-atishay approved these changes
This looks more solid implementation then previous code

2024-11-29 23:09 UTC, commcheck396 approved these changes
The code is clean, well-organized, and easy to follow so far.

2024-11-29 23:17 UTC, merged